name = "denmelnychuk"
main = "src/pages/api/send-email.js"
compatibility_date = "2024-02-26"

# Environment variables are configured in Cloudflare Worker settings
# The [vars] section is required to reference environment variables
[vars]
POSTMARK_API_KEY = "" # Value is stored in Cloudflare Worker settings
