name = "denmelnychuk"
main = "src/pages/api/send-email.js"
compatibility_date = "2024-02-26"

# Environment variables are configured in Cloudflare Worker settings
# Do not hardcode sensitive values here
