name = "denmelnychuk"
main = "src/pages/api/send-email.js"
compatibility_date = "2024-02-26"

# Environment variables are set in Cloudflare Workers dashboard
[vars]

[build]
command = "npm run build"

[[rules]]
type = "ESModule"
globs = ["**/*.js"]

[site]
bucket = "./dist"

