name = "denmelnychuk"
type = "javascript"
usage_model = "bundled"
compatibility_date = "2024-02-26"

# Main entry point for the worker
main = "src/pages/api/send-email.js"

# Environment variables configuration
# Base variables (available in all environments)
[vars]

# Production environment variables
[env.production]
vars = { POSTMARK_API_KEY = "" }  # Production environment variable
