name = "denmelnychuk"
type = "javascript"
usage_model = "bundled"
compatibility_date = "2024-02-26"

# Main entry point for the worker
main = "src/pages/api/send-email.js"

# Environment variables configuration
# This section declares which variables your worker expects
[vars]
POSTMARK_API_KEY = "" # Value is stored in Cloudflare Worker settings
